language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t dalpengholic/docker-react -f Dockerfile.dev .


script:
    - docker run -e CI=true dalpengholic/docker-react npm run test
