language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t dalpengholic/docker-react -f Dockerfile.dev .


script:
    - docker run -e CI=true dalpengholic/docker-react npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-west-2-287692131334"
    bucket_path: "docker-react" # the same as app
    on:
        branch: master

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY